on: push
name: Clippy check
jobs:
    clippy_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: rustup component add clippy
            - uses: actions-rs-plus/clippy-check@v2
              with:
                  args: --all-features --all-targets
