on:
  workflow_dispatch:
  push:
name: CI
jobs:
    test:
        runs-on: ${{ matrix.runner }}
        strategy:
          matrix:
            build: [windows-msvc, linux-gnu]
            include:
              - build: windows-msvc
                target: x86_64-pc-windows-msvc
                runner: windows-latest
              - build: linux-gnu
                target: x86_64-unknown-linux-gnu
                runner: ubuntu-latest
        steps:
          - uses: actions-rust-lang/setup-rust-toolchain@v1
            with:
              toolchain: stable
              target: ${{ matrix.target }}
          - uses: actions/checkout@v4
          - run: cargo test --all-features

    clippy_check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            toolchain: stable
            components: clippy
        - uses: actions/checkout@v4
        - uses: actions-rs-plus/clippy-check@v2
          with:
              args: --all-features --all-targets
